app_name: "go-sample-app"
version: "1.0.0"
port: 8080
environment: "development"

database:
  host: "this-val-loaded-from-remote"
  port: 5432
  username: "postgres-from-remote"
  password: "password-from-remote"
  database: "sample_db-from-remote"

features:
  task_processing: true
  metrics_collection: true
  health_checks: true
  remote_config: true

metadata:
  description: "Sample GO application for Airflow Kubernetes integration"
  author: "Airflow Team"
  repository: "https://github.com/your-org/go-sample-app"
